name:  Test and build
on: [push,pull_request]
jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.0.2'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter test --coverage
      - run: flutter build apk --debug --split-per-abi
      - run: flutter build appbundle
      # Upload coverage reports to Codecov
      # https://github.com/marketplace/actions/codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage/lcov.info